#!/usr/bin/env python3
"""Export every theme's palette to JSON + CSS custom properties.

Parses the REAL source (DesignSystem.swift) so the values can't drift, and
folds in each theme's page-render filter + light/dark flag from AppTheme.swift.
Feed the JSON into a design tool to iterate on the colors.

Run:  python3 scripts/export-theme-palettes.py
Out:  docs/theme-palettes.json, docs/theme-palettes.css
"""
import json
import os
import re

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESIGN = os.path.join(HERE, "Sources/ReaderUI/DesignSystem.swift")
OUT_JSON = os.path.join(HERE, "docs/theme-palettes.json")
OUT_CSS = os.path.join(HERE, "docs/theme-palettes.css")

# palette var name -> (display name, isDark, page filter)
META = {
    "foldblue": ("Foldblue", False, "multiply #F1E3CC"),
    "light": ("Light", False, "none"),
    "sepia": ("Sepia", False, "multiply #F5EDE1"),
    "solarizedLight": ("Solarized Light", False, "multiply #FDF6E3"),
    "gruvboxLight": ("Gruvbox Light", False, "multiply #FBF1C7"),
    "bluefold": ("Bluefold", True, "invertTinted #0E2849"),
    "dark": ("Dark", True, "invert"),
    "gruvbox": ("Gruvbox", True, "invertTinted #282828"),
    "solarizedDark": ("Solarized Dark", True, "invertTinted #002B36"),
    "dracula": ("Dracula", True, "invertTinted #282A36"),
    "nord": ("Nord", True, "invertTinted #2E3440"),
}
ORDER = ["foldblue", "light", "sepia", "solarizedLight", "gruvboxLight",
         "bluefold", "dark", "gruvbox", "solarizedDark", "dracula", "nord"]


def parse_color(args):
    m = re.search(r"hex:\s*0x([0-9A-Fa-f]{6})", args)
    if m:
        hexv = "#" + m.group(1).upper()
    else:
        w = re.search(r"white:\s*([\d.]+)", args)
        v = int(round(float(w.group(1)) * 255))
        hexv = "#%02X%02X%02X" % (v, v, v)
    a = re.search(r"alpha:\s*([\d.]+)", args)
    alpha = round(float(a.group(1)), 3) if a else 1.0
    return hexv, alpha


def parse():
    src = open(DESIGN).read()
    palettes = {}
    for name in META:
        m = re.search(r"static let %s = DesignPalette\((.*?)\n    \)" % name,
                      src, re.S)
        if not m:
            continue
        fields = {}
        for fm in re.finditer(r"(\w+):\s*PlatformColor\(([^)]*)\)", m.group(1)):
            fields[fm.group(1)] = parse_color(fm.group(2))
        palettes[name] = fields
    return palettes


def build():
    palettes = parse()
    out = {}
    for name in ORDER:
        if name not in palettes:
            continue
        disp, is_dark, filt = META[name]
        colors = {}
        for field, (hexv, alpha) in palettes[name].items():
            colors[field] = hexv if alpha == 1.0 else {"hex": hexv, "alpha": alpha}
        out[name] = {"name": disp, "isDark": is_dark,
                     "pageFilter": filt, "colors": colors}
    with open(OUT_JSON, "w") as f:
        json.dump(out, f, indent=2)

    # CSS custom properties, one :root block per theme.
    lines = ["/* Bluefold theme palettes — generated by export-theme-palettes.py */"]
    for name in ORDER:
        if name not in out:
            continue
        lines.append(f'\n[data-theme="{name}"] {{')
        for field, val in out[name]["colors"].items():
            kebab = re.sub(r"(?<!^)(?=[A-Z])", "-", field).lower()
            if isinstance(val, dict):
                h = val["hex"].lstrip("#")
                r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
                lines.append(f"  --{kebab}: rgba({r}, {g}, {b}, {val['alpha']});")
            else:
                lines.append(f"  --{kebab}: {val};")
        lines.append("}")
    open(OUT_CSS, "w").write("\n".join(lines) + "\n")
    print("wrote", OUT_JSON, "and", OUT_CSS, f"({len(out)} themes)")


if __name__ == "__main__":
    build()
